<?php

namespace AppBundle\Repository;

/**
 * ChequesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequesRepository extends \Doctrine\ORM\EntityRepository
{
}
