<?php

namespace AppBundle\Repository;

/**
 * demoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demoRepository extends \Doctrine\ORM\EntityRepository
{
}
